# Generated by Django 2.2.5 on 2019-09-11 14:01

import bot.models_utils.jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vk_id', models.IntegerField(verbose_name='ID пользователя ВК')),
                ('wait_payload', bot.models_utils.jsonfield.JSONField(blank=True, null=True, verbose_name='Инфо об ожидаемом ответе')),
            ],
        ),
    ]
