# Generated by Django 2.2.5 on 2019-09-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя младенца')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Девочка'), (2, 'Мальчик')], verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='BabyUserVK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_date', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сообщения от юзера')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Baby')),
                ('user_vk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.UserVK')),
            ],
        ),
    ]
