# Generated by Django 2.2.5 on 2019-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_babyheight_babyweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babyhistory',
            options={'ordering': ('date_vk',)},
        ),
        migrations.AddField(
            model_name='babyhistory',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='В какой месяц ребёнка добавлено'),
        ),
        migrations.AddField(
            model_name='uservk',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='uservk',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
    ]
