# Generated by Django 2.2.5 on 2019-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20190921_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name': 'Ребёнок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='babyheight',
            options={'verbose_name': 'Показание роста', 'verbose_name_plural': 'Показания роста'},
        ),
        migrations.AlterModelOptions(
            name='babyhistory',
            options={'ordering': ('date_vk',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='babyhistoryattachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='babyuservk',
            options={'verbose_name': 'Связка пользователя с ребёнком', 'verbose_name_plural': 'Связки пользователей с детьми'},
        ),
        migrations.AlterModelOptions(
            name='babyweight',
            options={'verbose_name': 'Показание веса', 'verbose_name_plural': 'Показания веса'},
        ),
        migrations.AlterModelOptions(
            name='uservk',
            options={'verbose_name': ' Пользователь ВК', 'verbose_name_plural': ' Пользователи ВК'},
        ),
        migrations.AddField(
            model_name='uservk',
            name='album_pk',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Альбом #1'), (2, 'Альбом #2'), (3, 'Альбом #3')], default=1, verbose_name='Выбраный альбом'),
        ),
    ]
