# Generated by Django 2.2.5 on 2019-11-14 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0006_auto_20191024_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uservk',
            name='album_pk',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Альбом #1'), (2, 'Альбом #2'), (3, 'Альбом #3'), (4, 'Альбом #4')], default=1, verbose_name='Выбраный альбом'),
        ),
    ]
