# Generated by Django 2.2.5 on 2019-11-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20191114_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyhistoryattachment',
            name='background_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Позиция фото'),
        ),
    ]
